blank_issues_enabled: true
contact_links:
  - name: 👾 Discord
    url: https://discord.gg/jWwwsHRbnJ
    about: Join our Discord server for live discussions and support.
  - name: 👽 Reddit
    url: https://www.reddit.com/r/opire
    about: Go to our Reddit for general discussions and feedback.